name: Production CI/CD (Android)
on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci
        
      - name: Create service account key file
        run: |
          if [ -n "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}" ]; then
            echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}" > google-service-account.json
            echo "Google Play service account key created"
          else
            echo "Google service account key not provided, building without Google Play submission capability"
          fi

      - name: Build and submit to Google Play
        env:
          FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
          FOOTBALL_API_BASE_URL: ${{ secrets.FOOTBALL_API_BASE_URL }}
          EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }}
        run: eas build --auto-submit --profile production --platform android --non-interactive --no-wait
        
      - name: Publish EAS Update
        env:
          FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
          FOOTBALL_API_BASE_URL: ${{ secrets.FOOTBALL_API_BASE_URL }}
          EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }}
        run: eas update --auto --platform android